spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jira:
  base-url: ${JIRA_BASE_URL}

feign:
  client:
    username: ${FEIGN_CLIENT_USERNAME}
    api-token: ${FEIGN_CLIENT_API_TOKEN}
    config:
      jira-client:
        url: ${jira.base-url}



